# Generated by Django 4.1.4 on 2022-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="photo",
            field=models.ImageField(upload_to="portfolio/images"),
        ),
    ]
