# Generated by Django 4.1.4 on 2022-12-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0006_alter_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="photo",
            new_name="asd",
        ),
    ]
