# Generated by Django 4.1.4 on 2022-12-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0008_rename_asd_project_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
    ]
